# Generated by Django 5.2.17 on 2026-10-05 10:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('deadline', models.DateField()),
                ('official_website', models.URLField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=10)),
                ('minimum_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('maximum_family_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('any', 'Any'), ('female', 'Female'), ('male', 'Male'), ('other', 'Other')], max_length=10, null=True)),
                ('year_of_study', models.CharField(blank=True, choices=[('any', 'Any year'), ('1', 'First year'), ('2', 'Second year'), ('3', 'Third year'), ('4', 'Fourth year'), ('5', 'Fifth year'), ('6', 'Sixth year'), ('postgraduate', 'Postgraduate')], max_length=12, null=True)),
                ('pwd', models.BooleanField(blank=True, null=True)),
                ('minority', models.BooleanField(blank=True, null=True)),
                ('branch', models.ManyToManyField(blank=True, related_name='scholarships', to='scholarships.branch')),
                ('category', models.ManyToManyField(blank=True, related_name='scholarships', to='scholarships.category')),
                ('course', models.ManyToManyField(blank=True, related_name='scholarships', to='scholarships.course')),
                ('district', models.ManyToManyField(blank=True, related_name='scholarships', to='scholarships.district')),
                ('state', models.ManyToManyField(blank=True, related_name='scholarships', to='scholarships.state')),
            ],
            options={
                'ordering': ('deadline', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ('scholarship', 'name'),
                'constraints': [models.UniqueConstraint(fields=('scholarship', 'name'), name='unique_scholarship_required_document')],
            },
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='scholarship_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_percentage__isnull', True), models.Q(('minimum_percentage__gte', 0), ('minimum_percentage__lte', 100)), _connector='OR'), name='scholarship_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_cgpa__isnull', True), models.Q(('minimum_cgpa__gte', 0), ('minimum_cgpa__lte', 10)), _connector='OR'), name='scholarship_cgpa_range'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_family_income__isnull', True), ('maximum_family_income__gte', 0), _connector='OR'), name='scholarship_income_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_age__isnull', True), ('maximum_age__isnull', True), ('minimum_age__lte', models.F('maximum_age')), _connector='OR'), name='scholarship_age_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'active', 'closed'))), name='scholarship_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('gender__isnull', True), ('gender__in', ('any', 'female', 'male', 'other')), _connector='OR'), name='scholarship_gender_valid'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.CheckConstraint(condition=models.Q(('year_of_study__isnull', True), ('year_of_study__in', ('any', '1', '2', '3', '4', '5', '6', 'postgraduate')), _connector='OR'), name='scholarship_year_valid'),
        ),
    ]
